# Generated by Django 5.1.4 on 2025-01-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
