# Generated by Django 5.1.4 on 2025-01-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_cart_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
