# Generated by Django 5.1.4 on 2025-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_remove_payment_user_delete_cart_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
